[package]
name = "bevy_jam_5"
version = "0.1.0"
edition = "2021"

[dependencies]
avian2d = "0.1.1"
bevy = { version = "0.14.0", features = ["dynamic_linking"] }
bevy_asset_loader = { version = "0.21.0", features = ["2d"] }

[profile.dev.package."*"]
opt-level = 3

[profile.dev]
opt-level = 1
