[package]
name = "bevy_jam_5"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.14.0", features = ["dynamic_linking"] }

[profile.dev.package."*"]
opt-level = 3

[profile.dev]
opt-level = 1

